pipeline:
    build:
        image: golang
        commands:
        - go build
        - go test
        - ls
        - pwd

    work:
        image: 598240822331.dkr.ecr.us-east-1.amazonaws.com/git
        commands:
        - git --version
        - ls

    notify:
        image: plugins/slack
        channel: test-drone
        username: ehernandez
        webhook: WEBHOOK