pipeline:
  build:
    image: golang
    commands:
      - go build
      - go test

    notify:
        image: plugins/slack
        channel: test-drone
        username: ehernandez
        webhook: https://hooks.slack.com/services/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