pipeline:
    build:
        image: golang
        commands:
        - go build
        - go test

    notify:
        image: plugins/slack
        channel: test-drone
        username: ehernandez
        webhook: WEBHOOK