pipeline:
    build:
        image: golang
        commands:
        - go build
        - go test
        - pwd

    work:
        image: 598240822331.dkr.ecr.us-east-1.amazonaws.com/git
        commands:
        - git --version

    aemsetup:
        image: 598240822331.dkr.ecr.us-east-1.amazonaws.com/git
        when:
            branch: [ master ]
        commands:
        - sleep 15
        - echo "done aem"

    maven:
        image: 598240822331.dkr.ecr.us-east-1.amazonaws.com/maven:3.3.3
        commands:
        - mvn --version

    notify:
        image: plugins/slack
        channel: test-drone
        username: ehernandez
        webhook: WEBHOOK
        when:
            status: [ success, failure ]

services:
    author:
        image: 598240822331.dkr.ecr.us-east-1.amazonaws.com/aem-develop:6.1-jdk7-xcqb3.0.97
        when:
            branch: [ develop, !master ]


